# Generated by Django 2.0 on 2017-12-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171219_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='description',
            field=models.CharField(max_length=4091),
        ),
    ]
