# Generated by Django 2.0 on 2017-12-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171219_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='description',
            field=models.CharField(max_length=64091),
        ),
    ]
