# Generated by Django 2.0 on 2017-12-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_profile_main_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='description',
            field=models.CharField(max_length=18000),
        ),
    ]
